version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:1.64.0
    environment:
      - TZ=${TZ}
      # (Plus tard, avec domaine/HTTPS)
      # - N8N_EDITOR_BASE_URL=https://<domain>
      # - WEBHOOK_URL=https://<domain>
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=PathPrefix(`/`)
      - traefik.http.routers.n8n.entrypoints=web
      - traefik.http.services.n8n.loadbalancer.server.port=5678

volumes:
  n8n_data:
    name: n8n_data